### PR TITLE
Update Docling to 1.20.0

### PR DESCRIPTION
**Pull request by dolfim-ibm**
## Why are these changes needed?

The Docling updates allow (among others)
- Support for Windows (Refs https://github.com/IBM/data-prep-kit/issues/644)
- Improved table results (e.g. identifying column headers)
- Use torch instead of onnx for all models

### CODE REVIEW

**Comment by touma-I** [comment]
Thanks @dolfim-ibm . Any ideas where the error comes from? cc; @daw3rd In case he had seen this before. 
```
Full diff:
  - <pyarrow.lib.ChunkedArray object at 0x7f010d07a070>
  ?                                            -------
  + <pyarrow.lib.ChunkedArray object at 0x7f00fcc64d10>
  ?                                          +++++++
    [
      [
  -     "#/main-text/1"
  ?      ^^         ^
  +     "$.main-text[1]"
  ?      ^^         ^ +
      ]
    ]
============================== 1 failed in 19.80s ==============================
make[2]: *** [../../../../.make.defaults:411: .defaults.test-src] Error 1
make[2]: Leaving directory '/home/runner/work/data-prep-kit/data-prep-kit/transforms/language/doc_chunk/ray'
make[1]: *** [../../../.make.defaults:125: .recurse] Error 2
make[1]: Leaving directory '/home/runner/work/data-prep-kit/data-prep-kit/transforms/language/doc_chunk'
make: *** [Makefile:42: test-src] Error 2
make: Leaving directory '/home/runner/work/data-prep-kit/data-prep-kit/transforms/language/doc_chunk'
Error: Process completed with exit code 2.
```

**Comment by dolfim-ibm** [comment]
> Thanks @dolfim-ibm . Any ideas where the error comes from? cc; @daw3rd In case he had seen this before.

it is known, fixing it.

**Review by daw3rd — APPROVED** [review]
lgtm

**Comment by shahrokhDaijavad** [comment]
@sujee If you want to test if @dolfim-ibm's latest version of docling (1.20.0) works on a notebook that uses pdf2parquet on a Windows machine as part of your RAG example (assuming you have access to a native Windows machine!), you can try:
pip install --extra-index-url https://testpypi.python.org/pypi 'data-prep-toolkit-transforms[pdf2parquet]==0.2.2.dev1' 
this version of docling is not in pypi's 0.2.2.dev1 and will be in the next release on pypi. 
cc: @touma-I

**Pull request merged**
