### PR TITLE
tips for running on google colab

### PR DESCRIPTION
**Pull request by sujee**
## Why are these changes needed?

To enable run DPK applications on google colab.

## Related issue number (if any).

#582

### CODE REVIEW

**Comment by sujee** [comment]
need to know where we can link to this document

**Review by daw3rd — COMMENTED** [review]
Where should this file be linked from?
Also `fdedupe` to `fedeup`, for consistency

**Comment by sujee** [comment]
>  Also `fdedupe` to `fedeup`, for consistency

You mean this?  These are program args for the fuzzy transform.

```python
    # infrastructure
    "fdedup_bucket_cpu": 0.3,
    "fdedup_doc_cpu": 0.3,
    "fdedup_mhash_cpu": 0.3,
    "fdedup_num_doc_actors": 1,
    "fdedup_num_bucket_actors": 1,
    "fdedup_num_minhash_actors": 1,
    "fdedup_num_preprocessors": 1,
```

**Comment by sujee** [comment]
> Where should this file be linked from? 

May be we can create a **Tips and Troubleshooting** section in the main README

I can use some input on this : @Bytes-Explorer @shahrokhDaijavad

**Comment by shahrokhDaijavad** [comment]
@sujee There are other Tips and Troubleshooting issues dispersed in various doc files in the repo (e.g., mac.md and memory.md files in the same place you have put your google-colab.md file). If we create such a section in the README file, it's better to consolidate all of them into one md file with different sections for different tips. I think at some point soon, we should do this, but for now, I think we should just add a link to a section of README file that I submitted a PR for earlier this morning (PR #593) (to be reviewed by Hima). In the new README, I have put your Google Colab example before setting the local environment and we can add a sentence there saying something like: **Though you won't need them for this simple example, here are some tips for running on Google Coalb** and add the link

**Comment by sujee** [comment]
@shahrokhDaijavad I like this idea :+1:

**Comment by Bytes-Explorer** [comment]
yes a good idea, @sujee do you want to update the readme with tips for trouble shooting based on your experience
________________________________
From: Sujee Maniyam ***@***.***>
Sent: 17 September 2024 01:20
To: IBM/data-prep-kit ***@***.***>
Cc: Hima Patel ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [IBM/data-prep-kit] tips for running on google colab (PR #587)

@ shahrokhDaijavad I like this idea 👍 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <IBM/data-prep-kit/pull/587/c2353785050@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍


@shahrokhDaijavad<https://github.com/shahrokhDaijavad> I like this idea 👍

**Comment by daw3rd** [comment]
> > Also `fdedupe` to `fedeup`, for consistency
> 
> You mean this? These are program args for the fuzzy transform.
> 
> ```python
>     # infrastructure
>     "fdedup_bucket_cpu": 0.3,
>     "fdedup_doc_cpu": 0.3,
>     "fdedup_mhash_cpu": 0.3,
>     "fdedup_num_doc_actors": 1,
>     "fdedup_num_bucket_actors": 1,
>     "fdedup_num_minhash_actors": 1,
>     "fdedup_num_preprocessors": 1,
> ```
No, i saw doc references to `fededupe` which is something new.   I think you mean `fdedup`.  Let's not introduce new terms

**Review by shahrokhDaijavad — APPROVED** [review]
LGTM

**Pull request merged**
