### PR TITLE
Organise examples by use cases 

### PR DESCRIPTION
**Pull request by Bytes-Explorer**
## Why are these changes needed?
Organise getting started examples by use cases. Have moved some duplicate files to archive for now. We can bring them back post discussion with the team

### CODE REVIEW

**Comment by shivdeep-singh-ibm** [comment]
moving notebooks to internal nested folders will break `examples/notebooks/code_developers`,
`Makefile` and `prepare_env.sh`, also need to be updated.

**Comment by Bytes-Explorer** [comment]
We are upgrading to the new notebook sample-notebook.ipynb and want everyone to use pip install. We are archiving the other notebooks for now and will eventually make them compatible with pip based installation or remove them.

**Review by shivdeep-singh-ibm — APPROVED** [review]

**Review by daw3rd — CHANGES_REQUESTED** [review]
Why keep the archive directory?

**Comment by Bytes-Explorer** [comment]
> Why keep the archive directory?

David, we will remove it once we upgrade all notebooks in a couple of days.

**Review by daw3rd — APPROVED** [review]
Prefer not to have leftover `archive` but in the interest of time/sharing...

**Pull request merged**
