### PR TITLE
Update transform_utils.py to apply ZSTD compression

### PR DESCRIPTION
**Pull request by yuanchi2807**
[Feature] pyarrow parquet write_table can save up to 30% storage with compression flag ‘ZSTD’ #403

## Related issue number (if any).
#403

### CODE REVIEW

**Review by blublinsky — APPROVED** [review]

**Comment by blublinsky** [comment]
@yuanchi2807 can you, please, fix the issues and complete this?

**Comment by yuanchi2807** [comment]
> @yuanchi2807 can you, please, fix the issues and complete this?

The assert error is surprising. I tried to kick off a retest but don't know how on this UI. Let me update the PR to see if a re-run starts automatically.

**Comment by yuanchi2807** [comment]
@blublinsky all checks passed. Thank you.

**Comment by daw3rd** [comment]
@yuanchi2807 there are lots of changes here, perhaps a merge with dev will help with that and the conflicts.

**Comment by yuanchi2807** [comment]
> @yuanchi2807 there are lots of changes here, perhaps a merge with dev will help with that and the conflicts.

I will take a different approach. Open a new branch based on the current dev. Change a couple of files and resubmit a new PR. Getting a bit painful with the one-line change.

**Comment by yuanchi2807** [comment]
Closing this PR and reopened #441 to avoid branch conflict resolution.

**Pull request closed without merging**
