### PR TITLE
Enable kfp in GH action for testing workflows 

### PR DESCRIPTION
**Pull request by revit13**
## Why are these changes needed?

Test noop workflow in GH action.

### CODE REVIEW

**Review by blublinsky — APPROVED** [review]
LGTM

**Review by roytman — APPROVED** [review]
LGTM

**Comment by daw3rd** [comment]
Is this going to significantly increase the amount of time to build a PR?

**Comment by revit13** [comment]
> Is this going to significantly increase the amount of time to build a PR?

Yes, the time of the longest step is 13 minutes instead of 5 minutes.
EDIT: currently in some PRs I see that test-universal finishes their tests after 9 min so that might not be big gap

**Pull request merged**
