### PR TITLE
Add delay before deleting ray cluster in kfp component.

### PR DESCRIPTION
**Pull request by revit13**
## Why are these changes needed?

For debugging purposes add delay before deleting ray cluster in kfp component.

### CODE REVIEW

**Comment by blublinsky** [comment]
I am not sure we need this. We already have delay in execution

**Comment by roytman** [comment]
> I am not sure we need this. We already have a delay in execution

Hi @blublinsky , it is a different delay, if somebody wants to debug the Ray cluster, this delay will allow it before destroying the Ray cluster.

**Comment by blublinsky** [comment]
> > I am not sure we need this. We already have a delay in execution
> 
> Hi @blublinsky , it is a different delay, if somebody wants to debug the Ray cluster, this delay will allow it before destroying the Ray cluster.

Oh, then yes. It was not clear. sorry

**Review by roytman — APPROVED** [review]
LGTM

**Pull request merged**
