### PR TITLE
[will be closed soon] Real cluster installation scripts and instructions

### PR DESCRIPTION
**Pull request by roytman**
## Why are these changes needed?
Updates instructions and installation scripts to deploy the project to a real cluster

## Related issue number (if any).

https://github.com/IBM/data-prep-kit/issues/94

Signed-off-by: Alexey Roytman [roytman@il.ibm.com](mailto:roytman@il.ibm.com)

### CODE REVIEW

**Comment by blublinsky** [comment]
Oh, can you please, remove all extra files. Its impossible to read

**Comment by roytman** [comment]
> Oh, can you please, remove all extra files. Its impossible to read

You are looking at the wrong PR. I agree with you, so I created a new one. https://github.com/IBM/data-prep-kit/pull/116

**Comment by roytman** [comment]
This PR will be closed soon

**Comment by roytman** [comment]
Replaced by https://github.com/IBM/data-prep-kit/pull/116

**Pull request closed without merging**
