### PR TITLE
Enhancements to the Table of the root README file

### PR DESCRIPTION
**Pull request by shahrokhDaijavad**
Break the table up into universal, language, code, import/export tables. Have links from the table to each transform directory/project.

Issue #494

### CODE REVIEW

**Comment by Bytes-Explorer** [comment]
Thanks @shahrokhDaijavad . I would suggest some minor changes. 

For universal, lets order by importance

My suggestion would be: exact dedup, fuzzy dedup, doc id annotation (lets call it unique id), and the rest can come in any order. 

For the language only part, lets rename [Split document to chunks] to Document Chunking for RAG, Chunk embeddings

In the import/export, why do we have a convert for PDF to parquet?

**Review by blublinsky — APPROVED** [review]

**Comment by shahrokhDaijavad** [comment]
Thanks, @Bytes-Explorer. Done.

**Review by daw3rd — APPROVED** [review]

**Comment by Bytes-Explorer** [comment]
@shahrokhDaijavad [Document Chunking for RAG, Chunk embeddings] are two separate modules. Chunk embeddings is what you have noted as text embeddings. So, we could have Document Chunking for RAG and Text embeddings. If somewhere we could make it clear that the text embeddings are used on the chunks, that will be great. 

 Also, may I suggest that we change repo level order to semantic file ordering. Can we add the link to this paper to the semantic file ordering module https://arxiv.org/pdf/2407.13739?

**Comment by Bytes-Explorer** [comment]
@shahrokhDaijavad Pls raise a new PR to address these changes https://github.com/IBM/data-prep-kit/pull/495#issuecomment-2286580284

**Pull request merged**
