### PR TITLE
remove unused Make targets

### PR DESCRIPTION
**Pull request by roytman**
## Why are these changes needed?

As part of the simplification process, this PR remove some unused (empty) Make targets

### CODE REVIEW

**Comment by revit13** [comment]
@roytman LGTM btw is there a way to suppress printing? `@` did not work for me...

**Review by revit13 — APPROVED** [review]

**Review by daw3rd — COMMENTED** [review]
If we're still using recursive, from the top, test, build set-versions, this is will now throw errors when doing these from the top.  DId you try thta?

**Comment by roytman** [comment]
> If we're still using recursive, from the top, test, build set-versions, this is will now throw errors when doing these from the top. DId you try thta?

Yes I tried it, see the updated recursion target

**Comment by daw3rd** [comment]
I think we're on another take with the PR #309 .  Can we close this?

**Comment by roytman** [comment]
> I think we're on another take with the PR #309 . Can we close this?

did you mean https://github.com/IBM/data-prep-kit/pull/297 ? or both :-)

**Pull request closed without merging**
