### PR TITLE
Modify superpipeline params type.

### PR DESCRIPTION
**Pull request by revit13**
## Why are these changes needed?

This PR contains the following changes:

1) Fixes `repo_level_ordering` and `header_cleanser` Makefile such that the CI-CD could compile the pipelines although they are part of the black list whcih means they will not be tested.
2) All simple KFP pipelines use a dictionary for JSON input parameters, which significantly simplifies editing of the parameters and reduce possible human mistakes. The Super pipelines were not updated according this new convention. The PR fixes it.
3) Finally, it moves super pipeline examples into the /examples folder, according to https://github.com/IBM/data-prep-kit/issues/772. 

In addition, this PR addresses issue #772 
## Related issue number (if any).

#772

### CODE REVIEW

**Review by roytman — APPROVED** [review]
LGTM, but let's see reactions on https://github.com/IBM/data-prep-kit/issues/772#

**Comment by touma-I** [comment]
@revit13 can you help me better understand how this PR addresses issue #772? This issue has been eluding us and I would be delighted to know that we are indeed talking about the same problem :-)

**Comment by touma-I** [comment]
I think the reference to #722 is NOT the correct one. Please confirm. thanks

**Comment by revit13** [comment]
> I think the reference to #722 is NOT the correct one. Please confirm. thanks

Yes it was a typo sorry about that. I updated the PR description based on @roytman comments. Thanks

**Pull request merged**
