### PR TITLE
Add pre commit gh action

### PR DESCRIPTION
**Pull request by shivdeep-singh-ibm**
## Why are these changes needed?
Enables running pre-commit check on the pushed commits or pull request.

### CODE REVIEW

**Review by blublinsky — APPROVED** [review]
LGTM

**Comment by daw3rd** [comment]
@shivdeep-singh-ibm maybe its best to start over with the few files needed for this action?  I recently did a PR that should have corrected all the pre-commit failures - and may be responsible for the conflicts above.  Hopefully we won't get these next time.

**Comment by revit13** [comment]
Hi @shivdeep-singh-ibm can you please also update .pre-commit-config.yaml file? (remove `IBM Confidential` header)

**Comment by revit13** [comment]
Please consider applying pre-commit only on the changes files in the pull request using ` --from-ref` and `--to-ref`. This way the fixes can be applied incrementally.

**Comment by touma-I** [comment]
This is not a high priority right now and it will have adverse impact on current PRs. This will be closed with no commit for now and picked later. @shivdeep-singh-ibm to creat an issue.

**Pull request closed without merging**
